modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/RodrigoAyuso/factory_blocks/issues"
license = "MIT"

[[mods]]
modId = "tyrian_blocks"
version = "${version}"
displayName = "Tyrian Blocks"
authors = "slaincow"
description = '''
Adds Tyrian Blocks to Chisel Reborn or Chipped
'''
logoFile = "assets/tyrian_blocks/icon.png"

[[dependencies.tyrian_blocks]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tyrian_blocks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.tyrian_blocks]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
