plugins {
    id 'dev.architectury.loom' version '1.7-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
}

architectury {
    minecraft = project.minecraft_version
}
def createVersionString() {
    def builder = new StringBuilder()

    builder.append(mod_version)

    builder.append('+mc').append(minecraft_version)

    return builder.toString()
}

allprojects {
    version = createVersionString()
    group = rootProject.maven_group
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        archivesName = "$rootProject.archives_name-$project.name"
    }

    repositories {
        maven { url = "https://maven.terraformersmc.com/" }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.layered {
            it.mappings("net.fabricmc:yarn:$rootProject.yarn_mappings:v2")
        }

        if (project.name == "forge") {
            modImplementation("maven.modrinth:chisel-reborn:forge-1.20.1-2.0.0")
            modImplementation("maven.modrinth:cryonicconfig:forge-1.20.1-1.0.0")
        } else {
            modImplementation("maven.modrinth:chisel-reborn:fabric-1.20.1-2.0.0")
            modImplementation("maven.modrinth:cryonicconfig:fabric-1.20.1-1.0.0")
        }
    }

    java {
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
            }
        }
        repositories {
            // Publishing repositories
        }
    }
}
